import{a as v,i as s,S as q}from"./assets/vendor-frHSA4Lh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const P="https://pixabay.com/api/",E="50172771-05af20c50899f4393bfb7f5e3";async function p(t,r){try{return(await v.get(P,{params:{key:E,q:t,page:r,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch{return s.error({title:"Error",message:"Something went wrong. Please try again!",position:"bottomRight"}),null}}const g=document.querySelector(".gallery"),f=document.querySelector(".loader"),h=document.querySelector(".gallery-load-btn"),B=new q(".gallery a");function y(t){const r=t.map(({webformatURL:a,largeImageURL:i,tags:e,likes:o,views:n,comments:b,downloads:S})=>`<li class="gallery-item-wrapper">
        <a class="gallery-image-link" href="${i}">
          <img class="gallery-image" src="${a}" alt="${e}" />
        </a>
        <div class="data">
          <p class="data-item">Likes<span class="data-item-numbers">${o}</span></p>
          <p class="data-item">Views<span class="data-item-numbers">${n}</span></p>
          <p class="data-item">Comments<span class="data-item-numbers">${b}</span></p>
          <p class="data-item">Downloads<span class="data-item-numbers">${S}</span></p>
        </div>
      </li>`).join("");g.insertAdjacentHTML("beforeend",r),B.refresh()}function R(){g.innerHTML=""}function L(){f.classList.remove("hidden")}function w(){f.classList.add("hidden")}function $(){h.classList.remove("hidden")}function d(){h.classList.add("hidden")}const m=document.querySelector(".form"),M=document.querySelector(".form-input"),I=document.querySelector(".gallery-load-btn");let c=1,u="",l=0;const O=15;function A(){const t=document.querySelector(".gallery-item-wrapper");if(!t)return;const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}m.addEventListener("submit",async t=>{t.preventDefault();const r=M.value.trim();if(r===""){s.warning({title:"Warning",message:"Please enter a search field!",position:"topLeft"});return}u=r,c=1,l=0,R(),d(),L();try{const a=await p(u,c);if(!a||!a.hits.length){s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(a.hits),l=a.totalHits,l>O&&$()}catch{s.error({title:"Error",message:"Something went wrong.",position:"topRight"})}finally{w(),m.reset()}});I.addEventListener("click",async()=>{c+=1,L();try{const t=await p(u,c);if(!t||!t.hits.length){d(),s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}y(t.hits),A(),document.querySelectorAll(".gallery-item-wrapper").length>=l&&(d(),s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{s.error({title:"Error",message:"Something went wrong during loading more images.",position:"topRight"})}finally{w()}});
//# sourceMappingURL=index.js.map
