import{a as p,S as f,i as n}from"./assets/vendor-Bz4lgVUE.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const g="https://pixabay.com/api/",h="50172771-05af20c50899f4393bfb7f5e3";function y(a){return p.get(g,{params:{key:h,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(r=>r.data).catch(r=>{console.log(r)})}const c=document.querySelector(".gallery"),u=document.querySelector(".loader"),L=new f(".gallery a");function b(a){const r=a.map(({webformatURL:s,largeImageURL:i,tags:e,likes:t,views:o,comments:m,downloads:d})=>`<li class="gallery-item-wrapper">
        <a class="gallery-image-link" href="${i}">
          <img class="gallery-image" src="${s}" alt="${e}" />
        </a>
        <div class="data">
          <p class="data-item">Likes<span class="data-item-numbers">${t}</span></p>
          <p class="data-item">Views<span class="data-item-numbers">${o}</span></p>
          <p class="data-item">Comments<span class="data-item-numbers">${m}</span></p>
          <p class="data-item">Downloads<span class="data-item-numbers">${d}</span></p>
        </div>
      </li>`).join("");c.innerHTML=r,L.refresh()}function S(){c.innerHTML=""}function v(){u.classList.remove("hidden")}function w(){u.classList.add("hidden")}const q=document.querySelector(".form"),l=document.querySelector(".form-input");q.addEventListener("submit",a=>{a.preventDefault();const r=l.value.trim();if(r===""){n.warning({title:"Warning",message:"Please enter a search field!",position:"topLeft"});return}S(),v(),y(r).then(s=>{if(!s.hits.length){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(s.hits),l.value=""}).catch(s=>{n.error({title:"Error",message:"Something went wrong.",position:"topRight"})}).finally(()=>{w()})});
//# sourceMappingURL=index.js.map
